### ISSUE TITLE
Implement register system with real api

### ISSUE THREAD

**Issue by GuroKung** [SixthFloor/FECS-Web#11]
send the data(email,password) to api

**Comment by GuroKung** [comment]
anyway the api just change again so the api path has to be fixed in order to make it work

**Comment by vincentvictor** [comment]
still have problem with register and login

**Comment by runyasak** [comment]
we will test register and login until the bug is fixed

**Comment by runyasak** [comment]
Register has some errors.

Checkout on: https://drive.google.com/open?id=0B7AwISLR7m1VRDhKMmdZN1dnUEk
