### ISSUE TITLE
Local Storage Service

### ISSUE THREAD

**Issue by 0xchimz** [SixthFloor/FECS-Web#12]
แยก Local Storage ออกมาเป็นอีก 1 service แล้วเรียกใช้

**Comment by GuroKung** [comment]
use localStorageService from  https://github.com/grevory/angular-local-storage

**Comment by GuroKung** [comment]
is there any problem with using .min.js file ? we don't really want to see the real code anyway

**Comment by vincentvictor** [comment]
ไม่แน่ใจว่าต้องคอมมเม้น task นี้หรือเปล่า

login.js

Fix description in comment to this one
(line 6)
@description Login service module is used to provide authentication service for the project. 

(line 7)
I have to idea what you have written. It's not a sentence. Can you please explain in Thai?

**Comment by vincentvictor** [comment]
route.js

Fix description and add name (line 3-5)
No space before star \* (line 4-5)
/**
*(SPACE)Route Module
*
*(SPACE)@description Route controls FECS application
*/

**Comment by GuroKung** [comment]
login - service module ใช้สำหรับ  authentication และจัดการ token 
controller อื่นๆเวลาจะจัดการอะไรที่เกี่ยวกับ authenticationให้ใช้ผ่านserviceตัวนี้ และ service ตัวนี้จะทำหน้าที่ ยิง api(ไปที่ฝั่ง bacnkend) และเอาtokenมาจัดการโดยจะทำการจัดเก็บและเรียกใช้ผ่านทางlocalStorageServiceอีกที

**Comment by vincentvictor** [comment]
Edit  (line 7). Is that okay?
"every controller that have to identify the customer, authentication service has to implement this service"

to

"The controllers which are related to authentication implement this service.
The login service derived token from API through localStorageService."

**Comment by GuroKung** [comment]
No, it's wrong about token and api . I have edit the description could you please translate it again with a little more details ?

**Comment by vincentvictor** [comment]
The controllers which are related to authentication system implement this service.
 The login service call API to backend side, then backend side send back the token.
After that, login service calls localStorageService to store and use token.

**Comment by GuroKung** [comment]
That's okay I think, next time  when we have a problem with description I recommend you to create new issue instead.
