### ISSUE TITLE
Navigation bar directive

### ISSUE THREAD

**Issue by vincentvictor** [SixthFloor/FECS-Web#13]
src/templates/navbar/css/navbar.css

fix the spaces. we use 2 spaces for indentation

https://docs.google.com/document/d/1J_RQNK671Xg3rzJQw9DS_OIIJ6yDBbtLOG0jZMvZEqA/edit#heading=h.v295hrpb60t

**Comment by iNont** [comment]
merged navbar+login UI with Guro's controller already,
so navbar.css was converted to navbar.scss in "scss/"

**Comment by vincentvictor** [comment]
I saw it. The navbar.scss is renamed to _navbar.scss

**Comment by vincentvictor** [comment]
navbar.js

I don't know whether you have done this file. Add jsdoc at the top of the code like below. This is all information that we can write. May need to edit if there is more details. You can see the similar format in home.js

/\* global angular */

/**
*(SPACE)Navigator Bar Module
*
*(SPACE)@description ...
*/
