### ISSUE TITLE
Add Product page

### ISSUE THREAD

**Issue by iNont** [SixthFloor/FECS-Web#16]
Create Add Product Page without connecting with Database
"/admin/product/add"
Controller is in "js/controller/product.js"
Service is in "js/service/product.js"

use admin account to test add product
- To add new product must enter productName, price, category, subCategory
- if description/dimensionDescription is empty, it's auto fill "-" (dash)
- No image uploader (i'll be another issue)

**Comment by vincentvictor** [comment]
1 No attribute of "SerialNumber of Product"
2 Product description, Dimension are stored in long String. How can you separate the line when the string is stored in database. 
TALK WITH BACKEND BEFORE CHANGING 

For example,
Length: 211 cm
Width: 168 cm
Footboard height: 38 cm
Headboard height: 100 cm
Mattress length: 202 cm
Mattress width: 152 cm

3 Subcategory (e.g Bed, Chair, Lamp) should be selected after selecting Category (e.g. bedroom, bathroom). Now, subcategory can be selected before category. 

When you select "kitchen" as category, the subcategory "bed", "sofabed" should not appear. 

4 No quantity attribute.

(optional) 
Add product by using text file with every details of all products.
