### ISSUE TITLE
Category  UI

### ISSUE THREAD

**Issue by GuroKung** [SixthFloor/FECS-Web#27]
re-modify category page UI

**Comment by vincentvictor** [comment]
The text in grey box (below category, above "All products" is 
Home  /\00a0 All 

Please fix this to the proper link

**Comment by GuroKung** [comment]
I already fix it

**Comment by vincentvictor** [comment]
http://localhost:3030/#/category/xxx

Waiting for decorating UI

**Comment by GuroKung** [comment]
I already done it but  it has a problem with bootstrap let's wait chin fix it

**Comment by vincentvictor** [comment]
Right now the Category page shows items in that category but i think UI and layout of Filter function needs to be fixed

**Comment by GuroKung** [comment]
now overall UI is working fine, for further improvement of UI
please create new issue separately for UI improvement and assign Chinclubi  

ไทย: คิดว่าควรแยก task สำหรับหน้าที่เสร็จแล้ว กับหน้าที่ตกแต่งให้สวยฟรุ๊งฟริ๊งออกจากกัน
- Filter ยังไม่ได้ทำ ตอนนี้มีไว้ประดับเฉยๆ 55555

**Comment by vincentvictor** [comment]
hey guro In Category page  i don't think product serial name is necessary to show on this page.  

จริงๆ  น่าจะเปลี่ยนจาก serial name เปนคำอธิบายสั้นๆ ว่าของคืออะไร เช่น เตียง ตู้ โตีะ บางสินค้าดูยาก และชื่อก็อ่านไม่ออก แต่มันจะมีปัญหากับ backend เพราะไม่ได้ design ไว้สำหรับ attribute นี้

**Comment by GuroKung** [comment]
ช่าย จริงๆ กะจะให้ Customer เห็นแค่ ชื่อ สินค้า กับราคา นั่นแหล่ะ 
ส่วน serial  number ทำไว้ให้admin เห็น แต่ตอนนี้ยังไม่ได้แยก
