### ISSUE TITLE
Change the name "product" to "furniture"

### ISSUE THREAD

**Issue by pNagi** [SixthFloor/FECS-Web#29]
"Product" is not correct way to call our product. It should be specify as furniture.

**Comment by GuroKung** [comment]
I think even it's actually furniture but it should generically refer to a word 'product'
according to my experience and most e-commerce website Ex. ikea 
also use the word 'product'. If you want the database to call it as 'Furniture' it fine just manage it on your own.

Also affect the project as describe below
- not the common way to use
- much rework while it is not necessary to be changed, slow down the project
- confusing in code and annoying

If you still want to change it show me some of your references

**Comment by waranyu1993** [comment]
it's okay if we use "product", then should I reword to "product"?

**Comment by vincentvictor** [comment]
In the meeting, we talked about not to change from product to furniture.  Well, keep using the word "product"
