### ISSUE TITLE
Login Authentication non-case sensitive

### ISSUE THREAD

**Issue by iNont** [SixthFloor/FECS-Web#30]
Email mustn't be case sensitive.
register with "jiratchaya@mail.com"
it could login with "Jiratchaya@Mail.COM"

**Comment by GuroKung** [comment]
fixed

**Comment by vincentvictor** [comment]
to Runyasak
You can test this fucntion

**Comment by runyasak** [comment]
This task is worked now.

**Comment by runyasak** [comment]
This task is worked now.
