### ISSUE TITLE
Implement category with real api

### ISSUE THREAD

**Issue by GuroKung** [SixthFloor/FECS-Web#32]
Using real api with category page when user click on (now there are only these categories in current api called)
- 'All products' 
- 'Bedroom' 
- 'Bathroom'  

the product is shown on the page by their categories

**Comment by GuroKung** [comment]
now we have category
- All products
- Bedroom
- Bathroom 
- Dinning Room 
- Kitchen 
- Living Room

ready for testing

**Comment by runyasak** [comment]
Some product data from API consist with 2 or more picture but it show only 1 picture on wesite. For now, we will test all descriptions except picture.

**Comment by runyasak** [comment]
We've done test script for ViewFurnitureCategory already. We will test later.
