### ISSUE TITLE
Cart page

### ISSUE THREAD

**Issue by GuroKung** [SixthFloor/FECS-Web#39]
view the shopping list

**Comment by GuroKung** [comment]
the page layout is ready waiting the API to finish
now we're using mock data and internal function data

**Comment by vincentvictor** [comment]
(Have to do) Fix the quantity column from limited number to a field which can  be edit number

(Done) Sent data to database when clicking checkout

**Comment by GuroKung** [comment]
Fix the quantity column from limited number to a field which can  be edit number 
create into new issue #63

**Comment by GuroKung** [comment]
done

**Comment by vincentvictor** [comment]
the red number on cart (on navigator bar) does not match to the quantity of product in cart
