### ISSUE TITLE
Design Product View

### ISSUE THREAD

**Issue by waranyu1993** [SixthFloor/FECS-Web#4]

**Comment by vincentvictor** [comment]
category.tmpl
product.tmpl

Indentation must be 2 spaces. Do not use tab.

**Comment by vincentvictor** [comment]
category.js

Description in comment is wrong. (line 4 and 6)
Product Controller Module >> Category Controller Module
@description Product Controller >> @description Controller Module

**Comment by vincentvictor** [comment]
Chin and I already edit that

**Comment by vincentvictor** [comment]
From SRS, we still miss some attributes: manufacturer, property and availability on this page. If you wanna change the requirement, we should do the requirement changes.
