### ISSUE TITLE
3 Steps Register page

### ISSUE THREAD

**Issue by vincentvictor** [SixthFloor/FECS-Web#7]
create page for register including register form

**Comment by vincentvictor** [comment]
divide the register page to 3 subpages:
- account information
- personal information
- credit card information

**Comment by vincentvictor** [comment]
Account Information

E-mail
- Quite annoying when typing first character in e-mail box and the message notifies "Re-enter E-mail address is not valid". The message is quite ambiguous.
- I suggest to check after filling the whole email so that you can check whether email is invalid (ex special characters, no address @mailxxx) or email is already used.

Password & Confirm password
- When typing first character, 2 messages are shown below confirm password: "Re-enter Password does not match" and "Re-enter Password should be between 8-20 characters" 
- The order of process should be 
  1)  Fill in password. Then system checks password is valid or not. If not it notifies a message (ex. password must contain... , password must not contain special characters)
  2)  Password is complete. Then filling Confirm password. The system checks Confirm password matches  Password or not.
- Now password can consist special characters (!@#$%...). Please fix to be only numeric and alphabet characters.

Bugs...
- After clicking the eye in the box, then change cursor to another box and back to first box. The eye is gone.
- Click next before filling email and password. The message shows "Invalid Form Please check for the required information". Then I type the right email and password, the message "Invalid..." still shows until clicking "next"

**Comment by vincentvictor** [comment]
Personal Information

First name, Last name, Province
-  It can consist special characters (!@#$%...). Fix to non-special characters

ZIP code, Phone number
-  It can consist special characters (!@#$%...) and alphabet. Fix to only numeric characters.

**Comment by GuroKung** [comment]
Move the UI fixing task into new issue #53
